### ISSUE TITLE
Initial setup related issue

### ISSUE THREAD

**Issue by dgtall** [sparklingpandas/sparklingpandas#127]
Hello,
I'm not sure if this can be raised as an issue. But couldn't find some other way to ask this question.
I have downloaded sparklingpandas zip file. 

I've added the folder to PYTHONPATH variable.

When I am trying to import it from python interactive shell, I'm getting an import error.
>>> import sparklingpandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sparklingpandas

I cannot use 'pip install' because pip is not installed on the machine I'm using. And I don't have much control on the machine since I'm not the root user of the machine.

**Comment by jhlch** [comment]
So, I think the way to install this locally without pip is to unzip the files. Then, there should be a setup.py file in the root dir of the directory created from unzipping it. You can then run `python setup.py install` and that should install everything locally, without pip.

**Comment by dgtall** [comment]
Thanks very much. This works!
