### ISSUE TITLE
Fix the extra "index" column showing up in groupBy

### ISSUE THREAD

**Issue by holdenk** [sparklingpandas/sparklingpandas#59]
When we do groupBy we get an extra index column sometimes (you can see by running the tests). We should figure out how to handle this/remove it.

**Comment by jhlch** [comment]
This is related to the discussion going on here [Issue 61](https://github.com/sparklingpandas/sparklingpandas/issues/61).

**Comment by holdenk** [comment]
This is resolved in https://github.com/sparklingpandas/sparklingpandas/pull/66
